package-lock.json, package.json, src/App.js, src/components/ui/LoadingSpinner.js, src/index.js, src/store/index.js
Install react-spinner, create LoadingSpinner component, place it to ui folder, initial setup redux
=>  react-spinner, initial setup redux

package-lock.json, package.json, public/index.html, src/App.js, src/components/BookConsultation/BookConsultation.js, src/components/Contact/Contact.js, src/components/Footer/Footer.js, src/components/Gallery/Gallery.js, src/components/Header/Header.js, src/components/Header/Header.module.css, src/components/Hero/Hero.js, src/components/MeetOurTeem/MeetOurTeem.js, src/components/Modal/Modal.js, src/components/Nav/Nav.js, src/components/Nav/Nav.module.css, src/components/Services/Services.js, src/components/SignatureDrinks/SignatureDrinks.js, src/components/SignatureDrinks/SignatureDrinksItem.js, src/components/Testimonials/Testimonials.js
Replace styles with classes importing css module files, add react-router-hash-link as dependency
=> replace styles with classes, import react-router-hash-link

src/components/Footer/Footer.js, src/components/Footer/Footer.module.css
=> Footer desktop.

src/components/Services/Services.js, src/components/Services/Services.module.css, src/index.css
Adjust Services section styles.
=> Services section styles.

src/components/BottomNav/BottomNav.js, src/components/BottomNav/BottomNav.module.css, src/pages/MainDisplay.js
Create bottom navbar, make it fixed and overflow.
=> Bottom navbar.

src/components/Nav/Nav.js, src/components/Nav/Nav.module.css
Adjust styles in Top Navbar mobile.
=> Styles in Top Navbar mobile.

src/components/About/About.js, src/components/About/About.module.css, src/index.css
Adjust styles in About mobile.
=> Styles in About mobile.

src/components/About/About.module.css, src/components/BottomNav/BottomNav.module.css, src/components/Services/Services.module.css
=> Services section mobile.

src/components/Nav/Nav.js, src/components/Nav/Nav.module.css, src/components/Services/Services.module.css
Add navbar mobile functionality.
=> Navbar mobile functionality.

src/components/MeetOurTeem/BartenderCard.js, src/components/MeetOurTeem/MeetOurTeem.js, src/components/MeetOurTeem/MeetOurTeemSlider.css, src/components/MeetOurTeem/MeetOurTeemSlider.js
Add styles to mobile Meet Our Team.
=> Styles to mobile Meet Our Team.

src/components/MeetOurTeem/MeetOurTeem.js, src/components/MeetOurTeem/MeetOurTeemDisplay.js, src/components/MeetOurTeem/MeetOurTeemSlider.js
Extract a slider in MeetOurTeam to a separate component MeetOurTeamSlider.
=> MeetOurTeamSlider.

src/App.js, src/components/Auth/LogInForm.js, src/components/Auth/LogInForm.module.css, src/components/Auth/PasswordChangeForm.js, src/components/Auth/PasswordChangeForm.module.css, src/components/Footer/Footer.js, src/context/auth-context.js, src/pages/AdminDashboard.js
Add Password change styles, 
Protect frontend pages,
Persist auth with local storage functionality,
Add logout functionality.
=> Password change styles, frontend pages protection, persist auth, logout

src/App.js, src/components/Auth/LogInForm.js, src/components/Auth/PasswordChangeForm.js, src/components/Nav/Nav.js, src/context/auth-context.js, src/pages/AdminDashboard.js
Add password change functionality.
=> Password change functionality.

src/components/BottomNav/BottomNav.js, src/components/Footer/Footer.js, src/components/Footer/Footer.module.css, src/components/Hero/Hero.js, src/components/Hero/HeroBtn.js, src/components/Modal/Modal.js, src/components/Nav/Nav.js, src/context/modal-context.js, src/index.js, src/pages/MainDisplay.js
added context to footernav and navbar. Modal can be closed by clicking anywhere within the modal.
=> Fabian dev

public/index.html, src/AdminDashboard/components/NavSide/NavSide.js, src/ClientDisplay/components/Footer/Footer.js, src/ClientDisplay/components/Footer/Footer.module.css
Change route path from Footer to Admin page, About section.
=> Route path from Footer to Admin page, About section.

src/AdminDashboard/components/AboutDashboard/AboutDashboard.js, src/AdminDashboard/components/ui/DashboardContainer/DashboardContainer.js, src/AdminDashboard/components/ui/DashboardFooter/DashboardFooter.js, src/AdminDashboard/components/ui/DashboardFooter/DashboardFooter.module.css, src/AdminDashboard/components/ui/DashboardMain/DashboardMain.js, src/AdminDashboard/components/ui/DashboardMain/DashboardMain.module.css
Add dashboard footer component.
=> Dashboard footer component.

package-lock.json, package.json, src/AdminDashboard/components/NavSide/NavSide.js, src/AdminDashboard/components/TeamDashboard/BartenderDashboardCard.js, src/AdminDashboard/components/TeamDashboard/BartendersDashboardDisplay.js, src/AdminDashboard/components/TeamDashboard/TeamDashboardDisplay.js, src/AdminDashboard/components/ui/AddEditDelete/AddEditDelete.js, src/AdminDashboard/components/ui/AddEditDelete/DeleteData.js, src/ClientDisplay/components/MeetOurTeem/BartenderCard.js, src/index.js, src/store/enable-delete-slice.js, src/store/index.js
Add enable-delete-slice with redux.
=> Enable-delete-slice with redux.

src/AdminDashboard/components/TeamDashboard/BartenderDashboardCard.js, src/AdminDashboard/components/TeamDashboard/TeamDashboardDisplay.js, src/AdminDashboard/components/ui/AddEditDelete/AddEditDelete.js, src/AdminDashboard/components/ui/AddEditDelete/DeleteData.js, src/ClientDisplay/components/About/About.js, src/pages/EditBartendersPage/EditBartendersPage.js, src/store/enable-edit-slice.js, src/store/index.js
Add enable-edit-slice with redux.
=> Add enable-edit-slice with redux.

src/AdminDashboard/components/TeamDashboard/BartendersDashboardDisplay.js, src/AdminDashboard/components/TeamDashboard/BartendersDashboardDisplay.module.css, src/AdminDashboard/components/TeamDashboard/TeamDashboard.js, src/AdminDashboard/components/ui/AddEditDelete/AddEditDelete.js, src/AdminDashboard/components/ui/DashboardMain/DashboardMain.module.css, src/ClientDisplay/components/About/About.js, src/ClientDisplay/components/Testimonials/Testimonials.css, src/pages/EditBartendersPage/EditBartendersPage.js
=> Team Dashboard

src/AdminDashboard/components/NavSide/NavSide.js, src/AdminDashboard/components/ServicesDashboard/ServicesDashboard.js, src/AdminDashboard/components/ServicesDashboard/ServicesDashboardCard.js, src/AdminDashboard/components/ServicesDashboard/ServicesDashboardDisplay.js, src/AdminDashboard/components/ServicesDashboard/ServicesDashboardDisplay.module.css, src/AdminDashboard/components/TeamDashboard/BartenderDashboardCard.js, src/AdminDashboard/components/TeamDashboard/BartendersDashboardDisplay.js, src/AdminDashboard/components/ui/AddEditDelete/EditBartender.js, src/AdminDashboard/components/ui/AddEditDelete/EditBartender.module.css, src/App.js, src/ClientDisplay/components/Services/Services.js, src/ClientDisplay/components/Services/Services.module.css, src/pages/EditServicesPage.js, src/store/activate-service-dashboard-slice.js, src/store/index.js
=> Add modal to Services.

src/index.css, src/pages/EditServicesPage.js, src/pages/EditServicesPage.module.css
Finish data update functionality on Service dashboard.
=> Finish data update functionality on Service dashboard.

public/index.html, src/AdminDashboard/components/BartendersDashboard/BartenderCardDashboard.js, src/AdminDashboard/components/BartendersDashboard/BartenderCardDashboard.module.css
Fix alignment of the Bartender card on dashboard.
=> Fix alignment of the Bartender card on dashboard.

src/AdminDashboard/components/HeroDashboard/HeroDashboard.js, src/AdminDashboard/components/HeroDashboard/HeroDisplayDashboard.js, src/AdminDashboard/components/HeroDashboard/HeroDisplayDashboard.module.css, src/AdminDashboard/components/NavSide/NavSide.js, src/AdminDashboard/components/ServicesDashboard/ServicesDashboardCard.js, src/AdminDashboard/components/ServicesDashboard/ServicesDashboardDisplay.module.css, src/AdminDashboard/components/ui/AddEditDelete/EditBartender.module.css, src/AdminDashboard/components/ui/DashboardHeader/DashboardHeader.js, src/App.js, src/ClientDisplay/components/Auth/LogInForm.js, src/ClientDisplay/components/Auth/PasswordChangeForm.js, src/ClientDisplay/components/Footer/Footer.js, src/ClientDisplay/components/Hero/Hero.module.css
Fix alignment of the Bartender card on dashboard,
Adjust styling on Hero section,
Adjust styles on the Book conversation btn,
Fix buttons on Services dashboard in mobile view.
=> Fix and adjust styles on Bartender card on dashboard,  Hero section client Services dashboard in mobile view

src/AdminDashboard/components/NavSide/NavSide.js, src/AdminDashboard/components/NavSide/NavSide.module.css
Fix NavSide height to improve layouts.
=> Fix NavSide height to improve layouts.

src/ClientDisplay/components/About/About.module.css
Align About dashboard section.
=> Align About dashboard section.

src/AdminDashboard/components/ServicesDashboard/ServicesDashboardCard.js, src/AdminDashboard/components/ServicesDashboard/ServicesDashboardDisplay.module.css
Adjust styles in Services dashboard.
=> Adjust styles in Services dashboard.

src/AdminDashboard/components/AboutDashboard/EditAboutPage.module.css, src/AdminDashboard/components/BartendersDashboard/BartenderCardDashboard.module.css, src/AdminDashboard/components/BartendersDashboard/BartendersDashboard.js, src/AdminDashboard/components/ServicesDashboard/ServicesDashboard.js, src/AdminDashboard/components/ServicesDashboard/ServicesDashboardDisplay.module.css, src/AdminDashboard/components/TestimonialsDashboard/TestimonialCardDashboard.module.css, src/AdminDashboard/components/TestimonialsDashboard/TestimonialsDisplayDashboard.module.css, src/AdminDashboard/components/ui/AddEditDelete/AddEditDelete.module.css, src/AdminDashboard/components/ui/AddEditDelete/DeleteData.module.css, src/AdminDashboard/components/ui/AddEditDelete/EditBartender.module.css, src/AdminDashboard/components/ui/AddEditDelete/EditData.module.css, src/ClientDisplay/components/Hero/Hero.module.css, src/ClientDisplay/components/MeetOurTeem/MeetOurTeem.js, src/ClientDisplay/components/MeetOurTeem/MeetOurTeemSlider.css, src/ClientDisplay/components/MeetOurTeem/MeetOurTeemSlider.js, src/ClientDisplay/components/Services/Services.module.css, src/index.css, src/pages/EditServicesPage.module.css
Add mobile style in Services dashboard.
=> Add mobile style in Services dashboard.

src/AdminDashboard/components/NavSide/NavSide.js, src/AdminDashboard/components/NavSide/NavSide.module.css, src/ClientDisplay/components/MeetOurTeem/MeetOurTeem.js, src/ClientDisplay/components/Nav/Nav.js, src/ClientDisplay/components/Nav/Nav.module.css
=> Add element to main navbar.

src/AdminDashboard/components/NavSide/NavSide.js
Update Client App link on main Navbar.
=> Update Client App link on main Navbar.

src/AdminDashboard/components/AboutDashboard/AboutDashboardDisplay.js, src/AdminDashboard/components/NavSide/NavSide.module.css, src/AdminDashboard/components/ServicesDashboard/ServicesDashboardDisplay.js, src/AdminDashboard/components/SignatureDrinksDashboard/SignatureDrinkCardDashboard.js, src/AdminDashboard/components/SignatureDrinksDashboard/SignatureDrinkCardDashboard.module.css, src/AdminDashboard/components/SignatureDrinksDashboard/SignatureDrinksDashboard.js, src/AdminDashboard/components/SignatureDrinksDashboard/SignatureDrinksDisplayDashboard.js, src/AdminDashboard/components/ui/AddUpdateModal/AddUpdateDataModal.js, src/App.js, src/ClientDisplay/components/About/About.module.css, src/ClientDisplay/components/Services/Services.module.css, src/pages/EditDrinks/EditDrinks.js
=> Adjust height of NavSide.

src/AdminDashboard/components/NavSide/NavSide.module.css, src/AdminDashboard/components/SignatureDrinksDashboard/SignatureDrinkCardDashboard.module.css, src/AdminDashboard/components/SignatureDrinksDashboard/SignatureDrinksDashboard.js, src/AdminDashboard/components/SignatureDrinksDashboard/SignatureDrinksDashboard.module.css
Create Signature Drinks Dashboard, set drinks data fetching from firebase, create update functionality and set modal, fix NavSide.
=> create Signature Drinks Dashboard, update NavSide.

src/AdminDashboard/components/SignatureDrinksDashboard/SignatureDrinkCardDashboard.module.css, src/AdminDashboard/components/ui/AddEditDelete/EditBartender.module.css, src/pages/EditDrinks/EditDrinks.js, src/pages/EditDrinks/EditDrinks.module.css
Create update form to update drink, style it the way the form looks like the card itself.
=> Create update form to update drink, style it the way the form looks like the card itself.

src/AdminDashboard/components/HeroDashboard/HeroDisplayDashboard.js, src/AdminDashboard/components/HeroDashboard/HeroDisplayDashboard.module.css, src/AdminDashboard/components/SignatureDrinksDashboard/SignatureDrinksDisplayDashboard.js
Display images on Hero dashboard with map, previously sorted objects in needed order to display images.
=> display images on Hero dashboard with map, sorted objects in the array

src/AdminDashboard/components/HeroDashboard/HeroCardDashboard.js, src/AdminDashboard/components/HeroDashboard/HeroDisplayDashboard.js, src/AdminDashboard/components/HeroDashboard/HeroDisplayDashboard.module.css, src/AdminDashboard/components/ui/AddEditDelete/EditHeroBtn.js, src/AdminDashboard/components/ui/AddUpdateModal/AddUpdateDataModal.js, src/App.js, src/index.css, src/pages/EditHero/EditHero.js, src/pages/EditHero/EditHero.module.css, src/pages/EditServicesPage.js, src/pages/EditServicesPage.module.css
Create update modal to update images on Hero dashboard.
=> Create update modal to update images on Hero dashboard.

src/AdminDashboard/components/HeroDashboard/HeroDisplayDashboard.module.css, src/index.css, src/pages/EditDrinks/EditDrinks.module.css, src/pages/EditHero/EditHero.module.css, src/pages/EditServicesPage.module.css
Make Landing page dashboard in mobile view.
=> Make Landing page dashboard in mobile view.

src/AdminDashboard/components/ui/DashboardFooter/DashboardFooter.module.css, src/index.css, src/pages/EditDrinks/EditDrinks.module.css, src/pages/EditServicesPage.module.css
Align Update data modal, put it in the middle of dashboards vs the middle of the whole screen that contains SideNav.
=> Align Update data modal in the middle of dashboards.

src/AdminDashboard/components/AboutDashboard/EditAboutPage.js, src/AdminDashboard/components/AboutDashboard/EditAboutPage.module.css
Update styles on EditAboutPage.
=> Update styles on EditAboutPage.

src/AdminDashboard/components/AboutDashboard/EditAboutPage.js, src/AdminDashboard/components/AboutDashboard/EditAboutPage.module.css
Finish updating styles in EditAboutPage.
=> Finish updating styles in EditAboutPage.

src/AdminDashboard/components/AboutDashboard/EditAboutPage.js, src/AdminDashboard/components/AboutDashboard/EditAboutPage.module.css, src/pages/EditTestimonials/AddEditTestimonials.js, src/pages/EditTestimonials/AddEditTestimonials.module.css
Optimize styling on AddEditTestimonials modal form.
=> Optimize styling on AddEditTestimonials modal form.

src/AdminDashboard/components/AboutDashboard/EditAboutPage.js, src/AdminDashboard/components/AboutDashboard/EditAboutPage.module.css, src/pages/EditBartendersPage/AddEditBartender.module.css, src/pages/EditBartendersPage/AddEditBartendersPage.js, src/pages/EditTestimonials/AddEditTestimonials.js, src/pages/EditTestimonials/AddEditTestimonials.module.css
Improve styling on AddEtidBartender form.
=> Improve styling on AddEtidBartender form.

src/AdminDashboard/components/NavSide/NavSide.module.css
=> remove outline from sidenav
